[package]
name = "quickmd"
version = "0.1.0"
authors = ["Andrew Radev <andrey.radev@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
dirs = "2.0.2"
env_logger = "0.6.2"
gdk = "0.10.0"
gio = "0.6.0"
glib = "0.7.1"
gtk = { version = "0.6.0", features = ["v3_16"] }
log = "0.4"
notify = "4.0.12"
pulldown-cmark = "0.5.2"
structopt = { version = "0.3.5", default-features = false }
tempfile = "3.1.0"
webkit2gtk = "0.7.0"
