[package]
name = "quickmd"
version = "0.1.0"
authors = ["Andrew Radev <andrey.radev@gmail.com>"]
edition = "2018"

[dependencies]
webkit2gtk = "*"
pulldown-cmark = "*"
notify = "*"

[dependencies.gtk]
version = "0.6.0"
features = ["v3_16"]

[dependencies.glib]
version = "0.7.1"
