# The default zoom level of the webview. In case of a HiDPI display, it can be useful to set this
# to a higher value.
#
# In the UI, the zoom level can be changed in increments of 0.1 by holding the Control key and
# scrolling up or down.
#
zoom: 1.0

# The command-line components to launch an editor with the "e" key (or exec into one with "E"). The
# `{path}` placeholder will be replaced with the full path to the current markdown file.
#
# Other examples for editor command-lines:
#
#   - ["code", "{path}"]
#   - ["gnome-terminal", "--", "vim", "{path}"]
#   - ["alacritty", "-e", "vim", "{path}"]
#
editor_command: ["gvim", "{path}"]

# You can set your own keybindings, or unset the defaults by setting them to
# "Noop". See the API documentaiton for a full list of actions, under
# `ui::action::Action`.
#
# The keybindings are passed along to GDK:
#   - if given `key_char`, it's passed along to `Key::from_unicode`
#   - if given `key_name`, `Key::from_name` is called with it. So, "plus"
#     instead of "+".
#   - Modifiers that are supported: "control", "shift", "alt"
#
mappings: []
# mappings:
#   - { key_char: "q",     modifiers: [],          action: "Quit" }
#   - { key_name: "minus", modifiers: ["control"], action: "ZoomOut" }
