# The default zoom level of the webview. In case of a HiDPI display, it can be useful to set this
# to a higher value.
#
# In the UI, the zoom level can be changed in increments of 0.1 by holding the Control key and
# scrolling up or down.
#
zoom: 1.0

# The command-line components to launch an editor with the "e" key (or exec into one with "E"). The
# `{path}` placeholder will be replaced with the full path to the current markdown file.
#
# Other examples for editor command-lines:
#
#   - ["code", "{path}"]
#   - ["gnome-terminal", "--", "vim", "{path}"]
#   - ["alacritty", "-e", "vim", "{path}"]
#
editor_command: ["gvim", "{path}"]
